spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ManavAhlawat/SpringCloud_Microservices_Eureka_FeignClient.git
          searchPaths: configRepository
          username: manavahlawat95@gmail.com
          password: hellogithub18

          #basedir: /Users/shuyang/Dev/Itlize_Training/Micro-service/config-server/baseddir
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
management:
  endpoints:
    web:
      expose: "*"

